# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('subdomain', models.CharField(max_length=1024)),
                ('api_key', models.CharField(max_length=1024)),
            ],
        ),
    ]
