# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'A unique name for this drip.', max_length=255, unique=True, verbose_name=b'Drip Name')),
                ('from_email_name', models.CharField(blank=True, help_text=b'Set a name for a custom from email.', max_length=150, null=True)),
                ('from_email', models.EmailField(blank=True, help_text=b'Set a custom from email.', max_length=254, null=True)),
                ('subject_template', models.TextField(blank=True, null=True)),
                ('body_html_template', models.TextField(blank=True, help_text=b'You will have settings and user in the context.', null=True)),
                ('template', models.CharField(blank=True, choices=[(None, b'None'), (b'our_revolution_email.html', b'Our Revolution')], default=None, max_length=64, null=True)),
                ('target', models.CharField(blank=True, max_length=128, null=True)),
                ('limit', models.IntegerField(default=0, help_text=b'Leave 0 to fetch all objects.')),
                ('ordering', models.CharField(blank=True, help_text=b'Only used if you specify a limit. If so, by what criteria should we choose which objects make the cut?', max_length=128, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, help_text=b'A line or two about what this does, and why. Good for institutional knowledge', max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drip Campaign',
            },
        ),
        migrations.CreateModel(
            name='QuerySetRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[(b'filter', b'Filter'), (b'exclude', b'Exclude')], default=b'filter', max_length=12, verbose_name=b'Type')),
                ('field_name', models.CharField(max_length=128, verbose_name=b'Fields')),
                ('lookup_type', models.CharField(choices=[(b'exact', b'exactly'), (b'iexact', b'exactly (case insensitive)'), (b'contains', b'contains'), (b'icontains', b'contains (case insensitive)'), (b'regex', b'regex'), (b'iregex', b'contains (case insensitive)'), (b'gt', b'greater than'), (b'gte', b'greater than or equal to'), (b'lt', b'less than'), (b'lte', b'less than or equal to'), (b'startswith', b'starts with'), (b'endswith', b'starts with'), (b'istartswith', b'ends with (case insensitive)'), (b'iendswith', b'ends with (case insensitive)')], default=b'exact', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('field_value', models.CharField(help_text=b'Can be anything from a number, to a string. Or, do `now-7 days` or `today+3 days` for fancy timedelta.', max_length=255)),
                ('drip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queryset_rules', to='espresso.Drip')),
            ],
            options={
                'verbose_name': 'Targeting Rule',
            },
        ),
        migrations.CreateModel(
            name='SentDrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('from_email', models.EmailField(default=None, max_length=254, null=True)),
                ('from_email_name', models.CharField(default=None, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('drip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_drips', to='espresso.Drip')),
            ],
            options={
                'verbose_name': 'Sent Drip Email',
            },
        ),
    ]
