# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='template',
            field=models.CharField(blank=True, choices=[(None, b'None (Plain Text)'), (b'our_revolution_email.html', b'Our Revolution')], default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='querysetrule',
            name='field_value',
            field=models.CharField(blank=True, help_text=b'Can be anything from a number, to a string. Or, do `now-7 days` or `today+3 days` for fancy timedelta.', max_length=255),
        ),
    ]
