# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drip',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drip',
            name='ordering',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
