# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso', '0002_auto_20160307_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='drip',
            name='template',
            field=models.CharField(choices=[(None, b'None'), (b'bernie_stock.html', b'Bernie 2016 Stock')], default=None, max_length=64, null=True, blank=True),
        ),
    ]
