# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsEmailChapterSubscription',
            fields=[
                ('cons_email_chapter_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('isunsub', models.IntegerField()),
                ('unsub_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cons_email_chapter_subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstituentAddress',
            fields=[
                ('cons_addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_addr_type_id', models.IntegerField()),
                ('is_primary', models.IntegerField()),
                ('addr1', models.CharField(blank=True, max_length=255, null=True)),
                ('addr2', models.CharField(blank=True, max_length=255, null=True)),
                ('addr3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=16, null=True)),
                ('zip_4', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('addr_aug_ver', models.IntegerField()),
                ('addr_aug_dt', models.DateTimeField(blank=True, null=True)),
                ('geocoder_accuracy', models.IntegerField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('create_app', models.CharField(blank=True, max_length=128, null=True)),
                ('create_user', models.CharField(blank=True, max_length=128, null=True)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_app', models.CharField(blank=True, max_length=128, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'cons_addr',
                'managed': False,
            },
        ),
    ]
