# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0002_consemailchaptersubscription_constituentaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsGroup',
            fields=[
                ('cons_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('use_global_unsub', models.IntegerField()),
                ('is_banned', models.IntegerField()),
                ('activist_code_id', models.IntegerField()),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('create_app', models.CharField(blank=True, max_length=128, null=True)),
                ('create_user', models.CharField(blank=True, max_length=128, null=True)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_app', models.CharField(blank=True, max_length=128, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=128, null=True)),
                ('group_type', models.CharField(max_length=32)),
                ('sqd', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('members', models.IntegerField(blank=True, null=True)),
                ('unique_emails', models.IntegerField(blank=True, null=True)),
                ('unique_emails_subscribed', models.IntegerField(blank=True, null=True)),
                ('count_dt', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_id', models.IntegerField()),
                ('base_cons_group_id', models.IntegerField(blank=True, null=True)),
                ('membership_resource', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cons_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsPhone',
            fields=[
                ('cons_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_phone_type_id', models.IntegerField(blank=True, null=True)),
                ('is_primary', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('isunsub', models.IntegerField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('create_app', models.CharField(blank=True, max_length=128, null=True)),
                ('create_user', models.CharField(blank=True, max_length=128, null=True)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_app', models.CharField(blank=True, max_length=128, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cons_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendableConsGroup',
            fields=[
                ('cons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bsd.Constituent')),
                ('isunsub', models.IntegerField()),
            ],
            options={
                'db_table': 'cons_group_002b42d8d17e',
                'managed': False,
            },
        ),
    ]
