# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 05:09
from __future__ import unicode_literals

from django.db import migrations, models

import django.contrib.gis.db.models.fields
import localflavor.us.models



def populate_zip_codes_and_centroid(apps, schema_editor):
    
    from django.contrib.gis.gdal import DataSource
    from django.contrib.gis.utils import LayerMapping
    from django.contrib.gis.gdal.field import OFTString
    

    class ZipCodeFriendlyLayerMapping(LayerMapping):
        FIELD_TYPES = dict(LayerMapping.FIELD_TYPES, **{
            localflavor.us.models.USZipCodeField: OFTString,
        })
    
    ZipCode = apps.get_model('hydra', 'ZipCode')
    
    path = "data/zipcodes/cb_2015_us_zcta510_500k.shp"
    
    try:
        ds = DataSource(path)
    except:
        raise
        
    layermapping = ZipCodeFriendlyLayerMapping(ZipCode, path, {'zip': "ZCTA5CE10", 'geom': "POLYGON"})
    layermapping.save(verbose=True)
    
    for zipcode in ZipCode.objects.all():
        zipcode.centroid = zipcode.geom.centroid
        zipcode.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', localflavor.us.models.USZipCodeField()),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.RunPython(populate_zip_codes_and_centroid, reverse_code=migrations.RunPython.noop)
    ]
