# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0003_add_email_to_request_and_fix_related_names_on_through_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotionrequest',
            name='message',
            field=models.CharField(max_length=2048),
        ),
    ]
