# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0004_auto_20161103_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotionrequest',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'approved', b'Approved'), (b'sent', b'Sent'), (b'skipped', b'Skipped')], default=b'new', max_length=128),
        ),
    ]
