# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Group Name')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('signup_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('group_id', models.CharField(max_length=4, null=True, unique=True)),
                ('rep_email', models.EmailField(max_length=254, null=True, verbose_name='Contact Email')),
                ('rep_first_name', models.CharField(max_length=35, null=True, verbose_name='First Name')),
                ('rep_last_name', models.CharField(max_length=35, null=True, verbose_name='Last Name')),
                ('rep_postal_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code')),
                ('county', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code')),
                ('size', models.CharField(blank=True, max_length=21, null=True, verbose_name='Group Size')),
                ('last_meeting', models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Meeting')),
                ('meeting_address_line1', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address Line 1')),
                ('meeting_address_line2', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address Line 2')),
                ('meeting_postal_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code')),
                ('meeting_city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('meeting_state_province', models.CharField(blank=True, max_length=40, null=True, verbose_name='State/Province')),
                ('other_types_of_organizing', models.TextField(blank=True, max_length=250, null=True, verbose_name='Other Types of Organizing')),
                ('description', models.TextField(max_length=250, null=True, verbose_name='Description (250 characters or less)')),
                ('other_issues', models.TextField(blank=True, max_length=250, null=True, verbose_name='Other Issues')),
                ('constituency', models.TextField(blank=True, max_length=250, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL')),
                ('website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL')),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('other_social', models.TextField(blank=True, max_length=250, null=True, verbose_name='Other Social Media')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('signed-mou', 'Signed MOU'), ('approved', 'Approved'), ('removed', 'Removed')], default='submitted', max_length=16)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
