# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='local_groups_group',
        ),
    ]
